### ISSUE TITLE
MacBookPro 9.2 switching issues

### ISSUE THREAD

**Issue by londere** [ashessin/touchpad-indicator#72]
On a fresh install of Debian 10 touchpad works like a charm, if I plug my external mouse touchpad become unstable and also an external mouse. After installing this extension if I plug the external mouse and disable the touchpad and works as expected. 

However, after install pulseaudioeffects, the first issue is presented the external mouse become unstable and does not disable the touchpad and both become unstable.

Also found this behaviour :

![Screenshot at 2021-05-30 19-08-25](https://user-images.githubusercontent.com/47585952/120124903-1ce7f080-c17c-11eb-8e1f-ac22489a43bd.png)
but after the installation change to this:
![Screenshot at 2021-05-30 19-09-48](https://user-images.githubusercontent.com/47585952/120124927-338e4780-c17c-11eb-9f9e-90ad9e656661.png)

OS: Debian 10 (x64)
Touchpad Indicator Version: 2.2.2-0extras19.04.1
Mate Desktop
Display Server: X11
Installation Source: GitHub Repository

cat /proc/bus/input/devices:

`I: Bus=0019 Vendor=0000 Product=0005 Version=0000
N: Name="Lid Switch"
P: Phys=PNP0C0D/button/input0
S: Sysfs=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0D:00/input/input0
U: Uniq=
H: Handlers=event0 
B: PROP=0
B: EV=21
B: SW=1

I: Bus=0019 Vendor=0000 Product=0001 Version=0000
N: Name="Power Button"
P: Phys=PNP0C0C/button/input0
S: Sysfs=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0C:00/input/input1
U: Uniq=
H: Handlers=kbd event1 
B: PROP=0
B: EV=3
B: KEY=10000000000000 0

I: Bus=0019 Vendor=0000 Product=0003 Version=0000
N: Name="Sleep Button"
P: Phys=PNP0C0E/button/input0
S: Sysfs=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0E:00/input/input2
U: Uniq=
H: Handlers=kbd event2 
B: PROP=0
B: EV=3
B: KEY=4000 0 0

I: Bus=0019 Vendor=0000 Product=0001 Version=0000
N: Name="Power Button"
P: Phys=LNXPWRBN/button/input0
S: Sysfs=/devices/LNXSYSTM:00/LNXPWRBN:00/input/input3
U: Uniq=
H: Handlers=kbd event3 
B: PROP=0
B: EV=3
B: KEY=10000000000000 0

I: Bus=0019 Vendor=0000 Product=0006 Version=0000
N: Name="Video Bus"
P: Phys=LNXVIDEO/video/input0
S: Sysfs=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:01/LNXVIDEO:00/input/input4
U: Uniq=
H: Handlers=kbd event4 
B: PROP=0
B: EV=3
B: KEY=3e000b00000000 0 0 0

I: Bus=0010 Vendor=001f Product=0001 Version=0100
N: Name="PC Speaker"
P: Phys=isa0061/input0
S: Sysfs=/devices/platform/pcspkr/input/input5
U: Uniq=
H: Handlers=kbd event5 
B: PROP=0
B: EV=40001
B: SND=6

I: Bus=0019 Vendor=0000 Product=0006 Version=0000
N: Name="Video Bus"
P: Phys=LNXVIDEO/video/input0
S: Sysfs=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/LNXVIDEO:01/input/input6
U: Uniq=
H: Handlers=kbd event6 
B: PROP=0
B: EV=3
B: KEY=3e000b00000000 0 0 0

I: Bus=0019 Vendor=0000 Product=0000 Version=0000
N: Name="applesmc"
P: Phys=
S: Sysfs=/devices/platform/applesmc.768/input/input7
U: Uniq=
H: Handlers=event7 js0 
B: PROP=0
B: EV=9
B: ABS=3

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HDA Intel PCH Line"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:1b.0/sound/card0/input8
U: Uniq=
H: Handlers=event8 
B: PROP=0
B: EV=21
B: SW=2000

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HDA Intel PCH Headphone"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:1b.0/sound/card0/input9
U: Uniq=
H: Handlers=event9 
B: PROP=0
B: EV=21
B: SW=4

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HDA Intel PCH SPDIF In"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:1b.0/sound/card0/input10
U: Uniq=
H: Handlers=event10 
B: PROP=0
B: EV=21
B: SW=2000

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HDA NVidia HDMI/DP,pcm=3"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input11
U: Uniq=
H: Handlers=event11 
B: PROP=0
B: EV=21
B: SW=140

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HDA NVidia HDMI/DP,pcm=7"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input12
U: Uniq=
H: Handlers=event12 
B: PROP=0
B: EV=21
B: SW=140

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HDA NVidia HDMI/DP,pcm=8"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input13
U: Uniq=
H: Handlers=event13 
B: PROP=0
B: EV=21
B: SW=140

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HDA NVidia HDMI/DP,pcm=9"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input14
U: Uniq=
H: Handlers=event14 
B: PROP=0
B: EV=21
B: SW=140

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HDA NVidia HDMI/DP,pcm=10"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input15
U: Uniq=
H: Handlers=event15 
B: PROP=0
B: EV=21
B: SW=140

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HDA NVidia HDMI/DP,pcm=11"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input16
U: Uniq=
H: Handlers=event16 
B: PROP=0
B: EV=21
B: SW=140

I: Bus=0003 Vendor=046a Product=001a Version=0111
N: Name="Cherry GmbH MultiBoard"
P: Phys=usb-0000:00:14.0-2.1/input0
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2.1/3-2.1:1.0/0003:046A:001A.0001/input/input17
U: Uniq=017893
H: Handlers=sysrq kbd event17 leds 
B: PROP=0
B: EV=120013
B: KEY=1000000000007 ff980000000007ff febeffdfffefffff fffffffffffffffe
B: MSC=10
B: LED=1f

I: Bus=0003 Vendor=05ac Product=8509 Version=0516
N: Name="FaceTime HD Camera (Built-in): "
P: Phys=usb-0000:00:1a.0-1.1/button
S: Sysfs=/devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.1/1-1.1:1.0/input/input18
U: Uniq=
H: Handlers=kbd event18 
B: PROP=0
B: EV=3
B: KEY=100000 0 0 0

I: Bus=0003 Vendor=05ac Product=0253 Version=0219
N: Name="Apple Inc. Apple Internal Keyboard / Trackpad"
P: Phys=usb-0000:00:1d.0-1.8.3/input0
S: Sysfs=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.8/2-1.8.3/2-1.8.3:1.2/input/input19
U: Uniq=
H: Handlers=mouse0 event19 
B: PROP=0
B: EV=7
B: KEY=1f0000 0 0 0 0
B: REL=103

I: Bus=0003 Vendor=046a Product=001a Version=0111
N: Name="Cherry GmbH MultiBoard Keyboard"
P: Phys=usb-0000:00:14.0-2.1/input1
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2.1/3-2.1:1.1/0003:046A:001A.0002/input/input20
U: Uniq=017893
H: Handlers=sysrq kbd event20 
B: PROP=0
B: EV=100013
B: KEY=1000000000007 ff980000000007ff febeffdfffefffff fffffffffffffffe
B: MSC=10

I: Bus=0003 Vendor=046a Product=001a Version=0111
N: Name="Cherry GmbH MultiBoard"
P: Phys=usb-0000:00:14.0-2.1/input1
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2.1/3-2.1:1.1/0003:046A:001A.0002/input/input21
U: Uniq=017893
H: Handlers=event21 leds 
B: PROP=0
B: EV=120001
B: LED=100

I: Bus=0003 Vendor=046a Product=001a Version=0111
N: Name="Cherry GmbH MultiBoard"
P: Phys=usb-0000:00:14.0-2.1/input1
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2.1/3-2.1:1.1/0003:046A:001A.0002/input/input22
U: Uniq=017893
H: Handlers=event22 
B: PROP=0
B: EV=9
B: ABS=10000000000

I: Bus=0003 Vendor=056e Product=0129 Version=0111
N: Name="ELECOM TrackBall Mouse EX-G Pro TrackBall"
P: Phys=usb-0000:00:14.0-2.3/input0
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2.3/3-2.3:1.0/0003:056E:0129.0003/input/input23
U: Uniq=4E32E9A0F9
H: Handlers=sysrq kbd event23 leds 
B: PROP=0
B: EV=120013
B: KEY=1000000000007 ff9f207ac14057ff febeffdfffefffff fffffffffffffffe
B: MSC=10
B: LED=1f

I: Bus=0003 Vendor=056e Product=0129 Version=0111
N: Name="ELECOM TrackBall Mouse EX-G Pro TrackBall"
P: Phys=usb-0000:00:14.0-2.3/input1
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2.3/3-2.3:1.1/0003:056E:0129.0004/input/input24
U: Uniq=4E32E9A0F9
H: Handlers=mouse1 event24 
B: PROP=0
B: EV=17
B: KEY=ff0000 0 0 0 0
B: REL=1943
B: MSC=10

I: Bus=0003 Vendor=056e Product=0129 Version=0111
N: Name="ELECOM TrackBall Mouse EX-G Pro TrackBall Consumer Control"
P: Phys=usb-0000:00:14.0-2.3/input2
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2.3/3-2.3:1.2/0003:056E:0129.0005/input/input25
U: Uniq=4E32E9A0F9
H: Handlers=kbd event25 
B: PROP=0
B: EV=13
B: KEY=40000000000000 0 302000000 387858411801 1e000000000000 0
B: MSC=10

I: Bus=0003 Vendor=056e Product=0129 Version=0111
N: Name="ELECOM TrackBall Mouse EX-G Pro TrackBall System Control"
P: Phys=usb-0000:00:14.0-2.3/input2
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2.3/3-2.3:1.2/0003:056E:0129.0005/input/input26
U: Uniq=4E32E9A0F9
H: Handlers=kbd event26 
B: PROP=0
B: EV=13
B: KEY=4000 0 0
B: MSC=10

I: Bus=0003 Vendor=05ac Product=8242 Version=0111
N: Name="Apple Computer, Inc. IR Receiver"
P: Phys=usb-0000:00:1d.0-1.8.2/input0
S: Sysfs=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.8/2-1.8.2/2-1.8.2:1.0/0003:05AC:8242.0007/input/input28
U: Uniq=
H: Handlers=kbd event28 
B: PROP=0
B: EV=100003
B: KEY=10c0000800 c000000000000 10000000

I: Bus=0003 Vendor=05ac Product=0253 Version=0111
N: Name="Apple Inc. Apple Internal Keyboard / Trackpad"
P: Phys=usb-0000:00:1d.0-1.8.3/input0
S: Sysfs=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.8/2-1.8.3/2-1.8.3:1.0/0003:05AC:0253.0008/input/input29
U: Uniq=
H: Handlers=sysrq kbd event29 leds 
B: PROP=0
B: EV=120013
B: KEY=10000 0 0 0 1007b00011007 ff9f217ac14057ff ffbeffdfffefffff fffffffffffffffe
B: MSC=10
B: LED=1f
`
X input devices:
    ```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ ELECOM TrackBall Mouse EX-G Pro TrackBall	id=14	[slave  pointer  (2)]
⎜   ↳ Apple Inc. Apple Internal Keyboard / Trackpad	id=20	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Video Bus                               	id=8	[slave  keyboard (3)]
    ↳ Power Button                            	id=9	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=10	[slave  keyboard (3)]
    ↳ Cherry GmbH MultiBoard                  	id=11	[slave  keyboard (3)]
    ↳ Cherry GmbH MultiBoard Keyboard         	id=12	[slave  keyboard (3)]
    ↳ ELECOM TrackBall Mouse EX-G Pro TrackBall	id=13	[slave  keyboard (3)]
    ↳ ELECOM TrackBall Mouse EX-G Pro TrackBall Consumer Control	id=15	[slave  keyboard (3)]
    ↳ ELECOM TrackBall Mouse EX-G Pro TrackBall System Control	id=16	[slave  keyboard (3)]
    ↳ FaceTime HD Camera (Built-in):          	id=17	[slave  keyboard (3)]
    ↳ Apple Computer, Inc. IR Receiver        	id=18	[slave  keyboard (3)]
    ↳ Apple Inc. Apple Internal Keyboard / Trackpad	id=19	[slave  keyboard (3)]

    ```

**Comment by ashessin** [comment]
The program in the screenshot is not this extension.
